version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: