version: "3.8"

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SEND_GRID_USERNAME: ${SEND_GRID_USERNAME}
      SEND_GRID_APIKEY: ${SEND_GRID_APIKEY}
      SEND_GRID_DOMAIN: ${SEND_GRID_DOMAIN}
    command: sh -c "./rails.sh"

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_NUMBER: ${TWILIO_NUMBER}
      SEND_GRID_USERNAME: ${SEND_GRID_USERNAME}
      SEND_GRID_APIKEY: ${SEND_GRID_APIKEY}
      SEND_GRID_DOMAIN: ${SEND_GRID_DOMAIN}
    volumes:
      - .:/data
    depends_on:
      - db
      - redis

volumes:
  data: